# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      # Group all GitHub Actions PRs into a single PR:
      all-github-actions:
        patterns:
          - "*"
  - package-ecosystem: "julia"
    directories: # Location of Julia projects
      - "/"
      - "/docs"
      - "/test"
    schedule:
      interval: "daily"
    groups:
      # Group updates for P4est_jll.jl and all other julia packages into separate PRs
      # because we usually want to update P4est_jll.jl separately.
      p4est-jll:
        patterns:
          - "P4est_jll"
      all-julia-packages-except-p4est-jll:
        patterns:
          - "*"
        exclude-patterns:
          - "P4est_jll"
